
package es.udc.fic.csi2122.baserest.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * The User entity
 * 
 * @author alfonso.landin@udc.es
 */
@Entity
public class User {

  /** Entity id, autogenerated */
  @Id
  @GeneratedValue
  private Long id;

  /** The user name. Names are unique in the application */
  @Column(unique = true)
  private String name;

  /** The user age */
  @Column
  private Integer age;

  /** Empty constructor as required by JPA */
  public User() {
  }

  /**
   * Convenience constructor for new users. Id is not set
   * 
   * @param name the user name
   * @param age  the user age
   */
  public User(String name, Integer age) {
    this.name = name;
    this.age = age;
  }

  /**
   * Get the user id
   * 
   * @return the user id
   */
  public Long getId() {
    return id;
  }

  /**
   * Set the user id
   * 
   * @param id the new user id
   */
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * Get the user name
   * 
   * @return the user name
   */
  public String getName() {
    return name;
  }

  /**
   * Set the user name
   * 
   * @param name the new user name
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Get the user age
   * 
   * @return the user age
   */
  public Integer getAge() {
    return age;
  }

  /**
   * Set the user age
   * 
   * @param age the new user age
   */
  public void setAge(Integer age) {
    this.age = age;
  }

  /**
   * Overridden toString for debugging
   */
  @Override
  public String toString() {
    return "User[id=" + id + ", name=" + name + ", age=" + age + "]";
  }
}
